#!/bin/bash
# Quick test plan for atomic counter boot hang fix

echo "=== Atomic Counter Boot Hang Fix - Test Plan ==="
echo ""
echo "Step 1: Rebuild kernel with fixes"
echo "  cd /home/jianyuew/repo/tmp/linux"
echo "  make -j$(nproc)"
echo "  sudo make modules_install install"
echo ""
echo "Step 2: Reboot into fixed kernel"
echo "  sudo reboot"
echo ""
echo "Step 3: Verify boot success"
echo "  - System should boot to login prompt (not hang)"
echo "  - Check dmesg for atomic counter messages:"
echo "    dmesg | grep -i atomic | grep -i memcg"
echo ""
echo "Step 4: Test basic functionality"
echo "  # Read memory stats"
echo "  cat /sys/fs/cgroup/memory.stat"
echo ""
echo "  # Create test cgroup"
echo "  sudo mkdir /sys/fs/cgroup/test_atomic"
echo "  cat /sys/fs/cgroup/test_atomic/memory.stat"
echo "  sudo rmdir /sys/fs/cgroup/test_atomic"
echo ""
echo "Step 5: Run performance tests (optional)"
echo "  cd /home/jianyuew/repo/tmp/linux/tools/testing/selftests/cgroup"
echo "  make"
echo "  sudo ./test_memcg_perf"
echo ""
echo "=== Alternative: Disable atomic counter if issues persist ==="
echo "  bash /home/jianyuew/repo/tmp/linux/fix_atomic_counter.sh"
echo "  make oldconfig && make -j$(nproc)"
echo "  sudo make modules_install install && sudo reboot"
